// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUC9L8F30zscFOdyDLPIuk542ohyN7VGA',
    appId: '1:371706293630:web:8721d4f9d53e508d3a972f',
    messagingSenderId: '371706293630',
    projectId: 'alba-1e168',
    authDomain: 'alba-1e168.firebaseapp.com',
    storageBucket: 'alba-1e168.firebasestorage.app',
    measurementId: 'G-MG6BYYLPSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB84M2rPstXZhKulq5qdEyPBjnQUZDkkao',
    appId: '1:371706293630:android:4226b42c831427bb3a972f',
    messagingSenderId: '371706293630',
    projectId: 'alba-1e168',
    storageBucket: 'alba-1e168.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1nRI4BAvs0aTQ4USigvQeziDi65sfSmo',
    appId: '1:371706293630:ios:9ea27da76cc816ae3a972f',
    messagingSenderId: '371706293630',
    projectId: 'alba-1e168',
    storageBucket: 'alba-1e168.firebasestorage.app',
    iosClientId:
        '371706293630-ttrnbds8iv5v20e0cohi57cfvvrhc7nn.apps.googleusercontent.com',
    iosBundleId: 'com.example.alba',
  );
}
